### ISSUE TITLE
How to set Maven Dependency Scope "Provided" for Debugging?

### ISSUE THREAD

**Issue by DaniGTA** [microsoft/vscode-java-debug#1025]
In Intelij i can choose to use the "Provided" scope:
![image](https://user-images.githubusercontent.com/20490672/123427017-62a1a880-d5c4-11eb-811e-d50718c3953f.png)

How i can set this in VSCode?

Info about Dependency Scopes:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

**Comment by RobberPhex** [comment]
I noticed that the default behave is `Include dependencies with "Provided" scope`.

That means if I write `ClassA` in folder `src/main/java/`, and there is a `ClassA` in provided dependency. Debugger will jump to `ClassA in provided dependency`. Which is not correct.

**Comment by testforstephen** [comment]
Currently we only support setting scope from "runtime" and "test" for Debugging.

> [provided](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope)
This is much like compile, but indicates you expect the JDK or a container to provide the dependency at runtime. For example, when building a web application for the Java Enterprise Edition, you would set the dependency on the Servlet API and related Java EE APIs to scope provided because the web container provides those classes. A dependency with this scope is added to the classpath used for compilation and test, but not the runtime classpath. It is not transitive.

Look at the definition of "provided" scope, it's used for compilation, not the runtime classpath. So not including it for Debugging is an expected behavior.

**Comment by testforstephen** [comment]
> That means if I write ClassA in folder src/main/java/, and there is a ClassA in provided dependency. Debugger will jump to ClassA in provided dependency. Which is not correct.

@RobberPhex, could you share a sample project to help reproduce this issue?
