### ISSUE TITLE
Debug java project remotely on raspberry pi 

### ISSUE THREAD

**Issue by remythales** [microsoft/vscode-java-debug#1114]
I have a maven java project on my raspberry pi and I am not able to remotely debug this project.
I can build the maven project but I am not able to connect the openJDK11.

The VS code java extension keeps crashing or hanging.
The java classpath cannot be found and the project not recognize even if my JDK is well installed and the JDK_HOME and JAVA_HOME are set properly. 

Do you have any advise? 

##### Environment
- Operating System: raspbian GNU/Linux
- JDK version: openjdk version "11.0.12" 2021-07-20
- Visual Studio Code version: 1.63.2
- Java extension version: 0.20.2
- Java Debugger extension version: 0.37.0

##### Steps To Reproduce
1. maven project on raspberry pi 4
2. Install and configure openJDK
2. connect to raspberry with Remote SSH v0.70.0
![vscode-java-remote-debugging](https://user-images.githubusercontent.com/68057059/150503674-1bacd22c-f331-40d5-b919-d42e8ee3c8ce.png)

**Comment by testforstephen** [comment]
Duplicated with this issue https://github.com/microsoft/vscode-java-pack/issues/887#issuecomment-1017031084

redhat.java 1.2.0 embeds a wrong JRE for Raspberry platform, which will be fixed in next version 1.3.0 of redhat.java.

So far, the workaround for you is to manually remove the directory /home/pi/.vscode/extensions/redhat.java-1.2.0/jre/17.0.1-macosx-aarch64.

**Comment by testforstephen** [comment]
Close this issue because **Language Support for Java(TM) by Red Hat** has released 1.3.0 to fix the wrong JDK issue.

**Comment by remythales** [comment]
Thanks for the reply, I will try that.
REmy

**Comment by remythales** [comment]
Yes it is solved. with the version 1.3.0 my java project was detected. 

Thanks a lot @testforstephen 
Cheers
