### ISSUE TITLE
Requires New Java Source Path for Every File I Directly Open

### ISSUE THREAD

**Issue by Adaptz** [microsoft/vscode-java-debug#1132]
When I try to open my school projects folder it requires me to create a java source path for each individual file which it didn't before.

##### Environment
- Operating System: Windows 10
- JDK version: jdk-17.0.2
- Visual Studio Code version: 1.65.1
- Java extension version: 1.4
- Java Debugger extension version: 0.38.0

##### Steps To Reproduce
1. Create new folder
2. Run any file 

[Project](https://github.com/Adaptz/Java-Coding-Class)
[Error](https://files.catbox.moe/z0mfpw.png)

##### Current Result
It makes me add a java source path for every file if I want to run it
##### Expected Result
Me opening the folder and it running fine like normal
##### Additional Informations
Happened after I did my first github push and reopened vscode I don't think it's related but might be nice to know.

**Comment by testforstephen** [comment]
this is by design. You're opening an unmanaged folder, you need to explicitly tell Java extension your source directories structure.

You can simply create a **.vscode/settings.json** in your root folder to define your source directories.
```json
{
    "java.project.sourcePaths": [
        "In-Class",
        "In-Class-2",
        "Lab-1",
        "Lab-2",
        "Lab-3",
        "Lab-4",
        "Lab-5",
        "Lab-6",
        "QuickCodeLabs",
        "Tests"
    ]
}
```

![image](https://user-images.githubusercontent.com/14052197/157792952-2070ceb2-fec8-4fa1-a0b9-12a4e0c5ee22.png)
