### ISSUE TITLE
com.sun.jdi.connect.TransportTimeoutException when vscode uses a large json env variables in envFile.

### ISSUE THREAD

**Issue by VinceVega7** [microsoft/vscode-java-debug#1386]
Hi,

When using a envfile in launch.json if the envfile has a very large variable value. eg. a large json.
In the terminal it slowly processes line by line, almost character by character and then a timeout occurs.

![image](https://github.com/microsoft/vscode-java-debug/assets/114009139/98a27ab4-d02e-483b-a1a8-f2b46eed27c0)

##### Environment
- Operating System: MacOsX
- JDK version: openjdk 17.0.6 2023-01-17 LTS
- Visual Studio Code version: 1.81.1
- Java extension version: v0.25.13
- Java Debugger extension version: v0.54.0
- pyenv shell 3.9.6

##### Steps To Reproduce
1. Create a envfile (.env) with only two variables.

eg.
SYSTEM_VAR_1=
SYSTEM_VAR_2=

Add a valid json as the value for each.

eg. SYSTEM_VAR_1='{"test:}' etc. but make the json about 30,000 characters.
[demo.zip](https://github.com/microsoft/vscode-java-debug/files/12498773/demo.zip)

It's a config all in json.

3. [step 2]
Use a launch.json like this:
        {
            "type": "java",
            "name": "DemoApplication",
            "request": "launch",
            "mainClass": "com.example.demo.DemoApplication",
            "projectName": "demo",
            "envFile": "${workspaceFolder}/.env"
        }

I attached a zip of a vscode project with an included .env that causes this error.

##### Current Result

timeout

##### Expected Result

no timeout and continues. faster would be better. 

##### Additional Informations
This works in intellij.

I have tried using different parameters in vscode but nothing works. It always timeouts.
Maybe the pyenv shell that gets invoked?

**Comment by testforstephen** [comment]
By default, Java debugger launches your application in the terminal. To support environment variable injection, it dumps all environment variables in the terminal, which can significantly slow down terminal rendering and result in a launch timeout. To avoid this timeout, you can launch the application in the console instead of the terminal. To do this, you can add `"console": "internalConsole"` to your launch.json file or `"java.debug.settings.console": "internalConsole"` to your VS Code settings.

**Comment by VinceVega7** [comment]
The launch .json with "console" , "internalConsole" worked for me. 
Thank you!
