### ISSUE TITLE
Option to specify Java path ?

### ISSUE THREAD

**Issue by edwardchanjw** [Microsoft/vscode-java-debug#186]
Option to specify Java Path such as Java 9.
Use Case: while some folk not must have legacy java for most other projects.

##### Additional Informations
[Similar Request](https://github.com/redhat-developer/vscode-java/issues/28)

**Comment by testforstephen** [comment]
The java debugger extension shares the same java runtime with `redhat-developer/vscode-java` extension. You can configure your JDK path in the user settings option `java.home`.

**Comment by yaohaizh** [comment]
Close this one as this issue is actually on the vscode java side.

**Comment by brunoborges** [comment]
It should be allowed to specify a custom JAVA_HOME in the `launch.json` file.

Please reopen and reconsider.

**Comment by arnaldobadin** [comment]
Agree. You should consider add a jdk_path option

**Comment by testforstephen** [comment]
No, we don't have plan to introduce a jdk_path option to launch.json. Because a custom jdk_path could be incompatible with the compiled class by Java tooling, and error prone.

However, we provide a command "**F1** -> **Java: Configure Java Runtime**" to allow you configure a different JDK for your project. Please have a try at it.

![image](https://user-images.githubusercontent.com/14052197/112920132-efaaa200-913a-11eb-978d-c63a63107c33.png)
