### ISSUE TITLE
The generated launch.json file is incomplete

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#191]
It is not stable repro.
Environment:
- Operating System:Mac Sierra 10.12.6
- JDK version:1.8.0_144
- Visual Studio Code version:1.18.1
- Java extension version:0.15.0
- Java Debugger extension version:daily build 110

Steps To Reproduce:
1. Open single folder
2. Press F5 choose java，the generated launch.json file is incomplete
![image](https://user-images.githubusercontent.com/28860891/33759564-c2029f20-dc3d-11e7-85a5-02491f49d110.png)

**Comment by adityasrini** [comment]
I'm having the same issue as well. I thought it was the documentation being wrong but now I see an "Auto generating configuration..." happening in the bottom bar so clearly that must not be working right.

My main class is 
```
package javaapplication1;

public class JavaApplication1 {
    public static void main(String[] args) {
        System.out.println("Greetings!");       
    }
}
```

and my launch.json file is attached as a txt.

Environment:
Operating System:Mac High Sierra 10.13.2 (17C88)
JDK version:9+181,
Visual Studio Code version:1.19.2
Java extension version:0.2.0
Debugger for Java version:0.5.0
[launch.json.txt](https://github.com/Microsoft/vscode-java-debug/files/1627374/launch.json.txt)

**Comment by akaroml** [comment]
@testforstephen  please take a look.

**Comment by andxu** [comment]
@adityasrini I think you have different understanding of the phase with us "If there's no debug configuration file launch.json in your project", here if you have no launch.json file in the .vscode file, we will generate one launch.json for you, if you have any modifications over the launch.json file, our plugin will not generate it for you because we think you as advanced user and have knowledge of parameters in launch.json, if you delete the mainClass, the plugin will ask you every time providing a list of run-able classes and do no modification to your launch.json because we cannot ensure our modification will not ruined your file.

**Comment by sallyur** [comment]
Test passed.

Environment

1. Mac Sierra 10.12.6
2. JDK 1.8.0_144
3. Visual Studio Code version: 1.22.2
4. Java extension version: 0.23.0
5. Java Debugger extension version: 0.8.0 (build: andy_private_build 40)
