### ISSUE TITLE
Show toString() values in variables windows

### ISSUE THREAD

**Issue by ivenxu** [microsoft/vscode-java-debug#315]
[Both in local variables and watch window, the debugger view shows the type of the complex object. It'll be really useful to show both type and toString() of the object]

##### Steps To Reproduce
1. put the following code in a test class
```
public void testComplexTypeVariables() {
        String hello = "How are you.";
        Date now = new Date();
        assertNotEquals("not expected to be the same.", hello, now);
    }
```
2. set break point on the assert line and start the debugger
3. look at the variables window

![image](https://user-images.githubusercontent.com/248655/41701891-7da3d196-7571-11e8-9de4-77db98012596.png)

##### Current Result
Showing Type only for complex object
##### Expected Result
to show both Type and toString() of the object. In the example, I expect to see ((now "2018-06-21 20:00:00.0" Date)) for the now variable.

**Comment by andxu** [comment]
Dup as https://github.com/Microsoft/vscode-java-debug/issues/236, should have a user setting by enable toString display

**Comment by ivenxu** [comment]
Actually, I don't think #236 and this are duplicated. What I'm after is simply displaying whatever the toString() in the view of variables, while #236 is about user provides a custom format then showing it in the view.

**Comment by ryno1234** [comment]
+1

**Comment by testforstephen** [comment]
For the classes that override 'toString' method, show `toString()` details.
For Collection and Map classes, show an additional `size=x` details.
For Entry, show `key:value` details.

![image](https://user-images.githubusercontent.com/14052197/58628378-17950880-830c-11e9-8bd8-8de85e7226d2.png)

**Comment by testforstephen** [comment]
0.19.0 is released. could you have a try?

// @ivenxu @ryno1234

**Comment by ivenxu** [comment]
> 0.19.0 is released. could you have a try?
> 
> // @ivenxu @ryno1234

Just tested, it works for me. Thank you guys a lot!

**Comment by lastant** [comment]
@testforstephen seems there is now a side effect that if an object like StringBuffer or String is very large the variables display crashes or timeouts, and no variables are displayed at all. Maybe you could show some meaningful error notification in this case. Otherwise it was difficult for me to figure out that the reason my list of local variables was empty was because of a large string in the variables and the showToString setting.

**Comment by testforstephen** [comment]
@lastant nice catch, will take a look at this edge case.

**Comment by SHASHANK0712** [comment]
Hello **@testforstephen**, I am currently **debugging inside a .class file** and in this class file I have a object - deviceBO - which I need to inspect. This deviceBO object's class DeviceBO has the following type hierarchy - 

1. DeviceBO class inherits Abstract class AbstractDeviceBO
2.  Abstract class AbstractDeviceBO inherits Class DeviceBaseBO
3. Class DeviceBaseBO inherits Abstract class AbstractDeviceBaseBO
4. Abstract class AbstractDeviceBaseBO inherits class GenericBO
5. Class GenericBO inherits class DataObject

Now this class **DataObject contains the toString() method**. Due to this arrangement, I am not able to see the toString() value of deviceBO object while inspecting through the Java Debugger. Also hover functionality is not working. PFB screenshots:

No toString() value being displayed -
<img width="268" alt="Picture1" src="https://github.com/microsoft/vscode-java-debug/assets/42925392/8dea3ecf-b81d-48a2-bd42-99e97c925637">

Hover functionality not working - 
<img width="641" alt="Picture2" src="https://github.com/microsoft/vscode-java-debug/assets/42925392/1f9ed581-0359-44e6-8c23-131762b85b4e">

Can you please let me know if I am missing anything or is the toString() functionality not supported in this extension?
