### ISSUE TITLE
"Failed to evaluate. Reason: Cannot evaluate because the thread is resumed." for Scanner(System.in)

### ISSUE THREAD

**Issue by stantonxu** [Microsoft/vscode-java-debug#328]
Debugger for Java seems not able to handle `new Scanner(System.in).next()`

When I try to run the following simple code with Debugger for Java,
```
        Scanner in = new Scanner(System.in);
        String input = in.next();
        in.close();
        System.out.println(input);
```
It will report the error mentioned in title.
`Failed to evaluate. Reason: Cannot evaluate because the thread is resumed.`

##### Environment
- Operating System: MacOS 10.12.4
- JDK version: 1.8.0
- Visual Studio Code version: 1.26.0 Insider
- Java extension version: 0.3.0
- Java Debugger extension version: 0.10.0

##### Steps To Reproduce
1. Include the above code in `main` function
2. Use Debugger for Java to run it

**Comment by andxu** [comment]
Dup as https://github.com/Microsoft/vscode-java-debug/issues/239:
in short:
"Cannot evaluate because the thread is resumed" is by design of java debug by Sun, you need to stop at a breakpoint/step before you could start evaluation.
The cause for this issue is user want to input by misunderstanding of vscode design for debug console(which is used to input text for evaluation)
If you do want to input in vscode, vscode has a solution which is to use "externalTerminal" or "integratedTerminal" in launch.json, see docuement about input in terminal at https://code.visualstudio.com/docs/editor/integrated-terminal

**Comment by stantonxu** [comment]
Thank you @andxu
