### ISSUE TITLE
when debug the terminal/console Chinese display garbled

### ISSUE THREAD

**Issue by shuqian** [microsoft/vscode-java-debug#361]
when debug with the integratedTerminal/internalConsole/externalTerminal Chinese display garbled
the java file is utf-8
##### Environment
- Operating System:MacOs 10.13.6
- JDK version:jdk1.8.0_111
- Visual Studio Code version:1.25.1
- Java extension version:0.3.0
- Java Debugger extension version:0.11.0

- ls the dir
![55t6gn.png](https://s1.ax2x.com/2018/08/11/55t6gn.png)

- compile the java code
![55tkcQ.png](https://s1.ax2x.com/2018/08/11/55tkcQ.png)

- externalTerminal mac default terminal
![55tlf2.png](https://s1.ax2x.com/2018/08/11/55tlf2.png)

- debug   integratedTerminal
![55tNQE.png](https://s1.ax2x.com/2018/08/11/55tNQE.png)

**Comment by testforstephen** [comment]
This is an encoding issue. Currently the jdt compiler will use the default OS encoding to compile the source file, no regarding what encode is used in VS Code Editor. If the user's system locale is not en-us, the default OS encoding is probably not UTF-8 compatible. In this case, the JDT compiler uses the wrong the encoding to parse the string constants of the source code, so that the generated *.class contains messy code.

Duplicated with the bug https://github.com/redhat-developer/vscode-java/issues/479

**Comment by yp0808** [comment]
meet the same problem

**Comment by testforstephen** [comment]
Recently we improved the encoding issues on Java debugger extension, could you try the latest version to see if the issue still exist? thanks.

https://github.com/microsoft/vscode-java-debug/blob/main/CHANGELOG.md#0370---2021-11-24
