### ISSUE TITLE
Show toString() values in hover tooltips

### ISSUE THREAD

**Issue by rothfels** [microsoft/vscode-java-debug#364]
Similar to https://github.com/Microsoft/vscode-java-debug/issues/315, it would be very useful to show the `.toString` of an object in the hover tooltip.

For example, in vanilla Eclipse debugger:

<img width="483" alt="screencapture" src="https://user-images.githubusercontent.com/1095573/44066628-2a773c86-9f26-11e8-88d8-b7683ae5886a.png">

vs. in VS Code, you also have to expand the elements to see what's inside:

<img width="617" alt="screencapture2" src="https://user-images.githubusercontent.com/1095573/44066708-a466b3c8-9f26-11e8-87f4-02a9f2dc82d9.png">

##### Steps To Reproduce
1. set breakpoint
2. hover over local variable

##### Current Result

See object explorer tooltip

##### Expected Result

Also see a useful `.toString`, as in Eclipse

**Comment by andxu** [comment]
@rothfels thank you for using our extension and opening up the concern for custom display, I can feel the eager needs to  this feature, actually I used this feature to display a list in the replies of this [issue](https://github.com/Microsoft/vscode-java-debug/issues/305), but due to the complicated logic of invoking evaluation engine and hard to bring manipulation ui in vscode for custom definition, the feature is not been put to start for now, but a quick/compromised solution may be only support a field and a method call without argument from a vscode workspace/project configuration, the <code>com.microsoft.java.debug.core</code> is a pure java maven project and perhaps a enthusiastic can contribute to that feature(we are on-progressing of providing documents to contributors about how to develop and test our extension), otherwise I would take a time for that.
the object formatter code is [here](https://github.com/Microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/formatter/ObjectFormatter.java#L42), and the unit test code [here](https://github.com/Microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/adapter/formatter/ObjectFormatterTest.java#L64)

**Comment by fbricon** [comment]
Eclipse allows users to define custom [detail formatter expressions](https://blog.codecentric.de/en/2013/04/again-10-tips-on-java-debugging-with-eclipse/) in its debugger, so that you can get a sensible String representation of an object, even if it doesn't override toString() itself.

**Comment by rothfels** [comment]
This is awesome, thank you so much @testforstephen! 🎉
