### ISSUE TITLE
Always launching jre instead of JDK

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#366]
Steps:
 Open any project  and write "new String("");"  and step in the String constructor, 

The variable should be two:
1. original
2. this

but actual the parameter for String constructor is arg0 which indicating that the program is running at jre env,eg:
```
n:\jdk1.8.0_181\jre\bin\java -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=localhost:9316,server=n,suspend=y -Dfile.encoding=UTF-8 -cp C:\work\vscode-java-debug\testprojects\8.nosource\bin;C:\work\vscode-java-debug\testprojects\8.nosource\lib\test1.jar;C:\work\vscode-java-debug\testprojects\8.nosource\lib\commons-io-2.5.jar NoSourceTest
```

**Comment by testforstephen** [comment]
The Java debugger will use the API `System.getProperty("java.home")` to resolve java bin path, and use it to launch the debuggee. For windows, the value of `System.getProperty("java.home")`  is read from the registry `HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft`, and it's generally pointing to the JRE.  This is the reason why the debuggee is launched in JRE instead of JDK.

To fix the issue, we need read the java bin path from the user environment variable `JAVA_HOME`.
