### ISSUE TITLE
Debugger for Java suddenly can't run

### ISSUE THREAD

**Issue by bobjiang1988** [Microsoft/vscode-java-debug#399]
[I have asked here](https://github.com/Microsoft/vscode/issues/57764#issue-356249221)
##### Environment
- Operating System: Ubuntu 18.04
- JDK version: 1.8
- Visual Studio Code version: 1.26.1

**Comment by andxu** [comment]
Can you put your pom.xml and the launch.json here?

**Comment by bobjiang1988** [comment]
@andxu [Click me to get the demo project.](https://github.com/bobjiang1988/java-debugger)

**Comment by andxu** [comment]
Your problem is lacking of snake yaml dependency, please add the following dependency
	<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>1.16</version>
		</dependency>
The java -jar target/demo-0.0.1-SNAPSHOT.jar is another way of launching different with our ways(we use target/classes as the class path rather than the demo-0.0.1-SNAPSHOT.jar, you can delete demo-0.0.1-SNAPSHOT.jar to see whether vscode java can be debug-able).

**Comment by bobjiang1988** [comment]
@andxu It's ok now. Thanks!
But I really don't know why it runs well in tomcat?

**Comment by andxu** [comment]
tomcat has the reference to snakeyaml

**Comment by andxu** [comment]
@bobjiang1988 , it is a bug caused by my change, see https://github.com/Microsoft/vscode-java-debug/issues/402, you would not need to add it  in next release
