### ISSUE TITLE
Code lenses for Run/Debug links on main methods don't show up immediately

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode-java-debug#438]
Code lenses for Run/Debug links on main methods don't show up immediately

##### Environment
- Operating System: macOS 10.13
- JDK version: 1.8
- Visual Studio Code version: 1.27.2
- Java extension version: 0.31.0
- Java Debugger extension version: 0.13.0

##### Steps To Reproduce
1. Create a simple java class
2. Copy and paste this main method into the class
```
	public static void main(String[] args) {
		System.out.print("hello");
	}
```
3. Run/Debug code lenses don't show up
4. Save file or type any character in the file
5. Run/Debug code lenses show up

##### Current Result
Run/Debug code lenses don't show up immediately

##### Expected Result
Run/Debug code lenses should show up immediately after the public static `main` method is added

**Comment by Eskibear** [comment]
Same behavior for the "main" snippet, it takes about 6 seconds to show up if you don't save or type any character.

**Comment by testforstephen** [comment]
When the user is editing the textDocument, there are two events happening in the Language Server Protocol level.
- vscode will call `provideCodeLenses` interface registered by java-debug to update CodeLens.
- vscode will send `document/didChange` to jdt.ls about the changed text.

The implementation of these two handlers both will operate the CompilationUnit object of the current file.  java-debug will read CompilationUnit to resolve main method.  On the other hand, vscode-java will update the CompilationUnit with the new changed text.  It's a resource contention problem. 

In the bug description, what java-debug got is an old CompilationUnit so that the user feels a delay.

**Comment by testforstephen** [comment]
Add logic to wait the DocumentLifeCycleHandler to finish updating.
