### ISSUE TITLE
Adding wrong jar version to the classpath

### ISSUE THREAD

**Issue by dampcake** [microsoft/vscode-java-debug#566]
The correct version of the JAR shows up Java Dependencies Pane but when executed a different version is added to the `-cp` arguments.

##### Environment
- Operating System: OSX
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.33.1
- Java extension version: 0.42.1
- Java Debugger extension version: 0.17.0

##### Steps To Reproduce
Sample: https://github.com/dampcake/incubator-druid/tree/fix-eclipse
run `mvn install -Pdist -DskipTests` to generate dependencies.

[Language Server Returning the wrong JAR](https://gist.github.com/dampcake/86979a1316c587b27709407552500604)

Config for project can be found in gist. Either way jetty-util should be 9.4.10 as shown in the dependency view.

##### Current Result
Wrong JAR dependency version is added to the classpath.

##### Expected Result
Correct JAR dependency version is added to the classpath.

##### Additional Informations
This project runs correctly in eclipse so I am not sure where the error is as the dependency view shows the correct JAR.

**Comment by yaohaizh** [comment]
@testforstephen Could you help take a look at this issue?

**Comment by testforstephen** [comment]
i can reproduce the issue, should be a bug.

**Comment by yaohaizh** [comment]
@jdneo Is this the same issue that tester fixed?

**Comment by rcl4444** [comment]
- Operating System: Windows_NT x64 10.0.18362
- JDK version: 1.8.0_181-1-redhat
- Visual Studio Code version: 1.33.1
- Java extension version: 0.7.1
- Java Debugger extension version: 0.18.0

I also encountered this problem.

**Comment by rcl4444** [comment]
in My situation, the Different versions exist simultaneously in the -cp arguments..

**Comment by testforstephen** [comment]
> [Dependency mediation](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html) - this determines what version of an artifact will be chosen when multiple versions are encountered as dependencies. Maven picks the "nearest definition". That is, it uses the version of the closest dependency to your project in the tree of dependencies. You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.
"nearest definition" means that the version used will be the closest one to your project in the tree of dependencies. For example, if dependencies for A, B, and C are defined as A -> B -> C -> D 2.0 and A -> E -> D 1.0, then D 1.0 will be used when building A because the path from A to D through E is shorter. You could explicitly add a dependency to D 2.0 in A to force the use of D 2.0.

When there are multiple versions for the same dependency existed in the dependency tree, maven will use BFS algorithm to use the nearest version as the target one.

Currently, java-debug used DFS algorithm to determine the dependency, that's the reason why the wrong JAR is added to the classpath. We will take advantage of the same mechanism as what maven did.

**Comment by testforstephen** [comment]
A new release is ready in vscode marketplace. Have a try!

//@dampcake @rcl4444
