### ISSUE TITLE
Remote Java debug is slow

### ISSUE THREAD

**Issue by ahmednrana** [microsoft/vscode-java-debug#596]
Remote Java debug is slow. It takes about 10 seconds to connect and 2-3 seconds to move from one line to another.

##### Environment
- Operating System: Mac OS on my machine and Redhat 7.3 on remote machine.
- JDK version: 1.8 on both
- Visual Studio Code version: 1.34
- Java extension version:  0.46.0
- Java Debugger extension version: 0.19.0

##### Steps To Reproduce
1. Connect to a remote Java program. I used WebSphere Application Server 9.0.0.7
2. It takes long time to connect ~4-20 seconds. 
3. It takes very long ~20 seconds to hit the first breakpoint. Stepping take about ~3 seconds
4. I tried with having nothing in my watches and by closing the debug view too. Still its slow.
5. I also tried clearing the workspace directory
**Note:**
If I use eclipse everything is instant.
Also, I tried using the Remote SSH extension of VS Code by copying my code to remote machine. Then the debugging in vscode is instant too.

The sample project is huge and private code. I wont be able to attach that.
Logs attached:
[vscode.txt](https://github.com/microsoft/vscode-java-debug/files/3272488/vscode.txt)
[vslang.log](https://github.com/microsoft/vscode-java-debug/files/3272490/vslang.log)

**Comment by testforstephen** [comment]
When you say eclipse is instant, do you have the specific performance data?

As i know, VS Code Java Debugger uses the same debug interface (JDI) as Eclipse, they should have similar performance. JDI protocol is chatty, and have lots of roundtrip even for a simple debug operation (such as step), that's the reason why remote debug is slow.

Yes, Remote SSH extension of VS Code is our recommendation for remote Java debugging, because it uses a more efficient protocol (VS Code Debug Adapter Protocol) to communicate between your local machine and remote server.

**Comment by ahmednrana** [comment]
If you can point me to how to get Eclipse specific data. I can pull that out.
Also, IntelliJ is instant too. If needed I can try to pull out that data too. Again I need some help in pointing me to which files to collect.
The non pleasant thing with remote SSH is that I had to copy the whole code to remote machine (and keep that updated too). Then it can be used to debug that machine. 
or Is there an alternate way to use remote SSH while keeping the code on my machine only?

**Comment by ahmednrana** [comment]
I am very sorry. The eclipse I had been testing with was on that same machine as the server, hence very fast. I tried eclipse from my machine and it is slow too like vs code. However, intelliJ is fast even while remote debugging from my machine.

**Comment by ahmednrana** [comment]
Closing it. Since it seems to be an Eclipse issue not Vs code
