### ISSUE TITLE
Debug console cannot be opened automatically in a new debug session if manually closed before

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-debug#597]
##### Environment
- Operating System: windows10/Mac
- JDK version: 8+11
- Visual Studio Code version: 1.35.1
- Java extension version: 0.46.0
- Java Debugger extension version: 0.19.0(build number:390)

##### Steps To Reproduce
1. Open a java project and press F5 to debug
2. The debug console will be opened automatically. After debugging, close the debug console manually.
3. Press F5 to debug again

##### Current Result
The debug console cannot be opened automatically

##### Expected Result
If the console uses an internal console, it should be opened every time you debug.

**Comment by testforstephen** [comment]
By design. This behavior is controlled by a launch.json config [`internalConsoleOptions`](https://code.visualstudio.com/updates/May_2016#_control-opening-the-debug-console). Its default value is `openOnFirstSessionStart`. If you want debug console opened every time, you need manually change it to `openOnSessionStart`.
