### ISSUE TITLE
Sometimes, code lenses for Run/Debug links on main methods don't show up immediately

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-debug#631]
##### Environment
- Operating System: Win/Mac/Linux
- JDK version:1.8/11/12
- Visual Studio Code version:1.37.0
- Java extension version: 0.47.0
- Java Debugger extension version:0.20.0

##### Steps To Reproduce
1. Git clone https://github.com/spring-projects/spring-petclinic.git.
2. Open project in VScode.
3. Open  PetClinicApplication.java.

##### Current Result
Sometimes, after project initialized, Run/Debug code lenses don't show up immediately until you edit java file or switch to another java file and switch back.

##### Expected Result
Run/Debug code lenses should show up immediately

**Comment by testforstephen** [comment]
This is side effect caused by the change that [removed the hard dependency for redhat.java extension](https://github.com/microsoft/vscode-java-debug/pull/617). 

Previously, when open a Java file, it will activate redhat.java extension first, then register codelens provider. It guarantees the Java extension is ready before calling codelens. 

Now open Java file, it will activate readhat.java extension, and register codelens provider at the same time. Calling codelens at this time does not guarantee it returns correct result because Java code may be not ready yet.  When you switch the editor back, the codelens shows up, that's because Java extension is ready at this time, calling codelens again will get the right result.
