### ISSUE TITLE
Failed to launch debuggee in terminal. Reason: Failed to launch debuggee in terminal. Reason: java.util.concurrent.TimeoutException: timeout

### ISSUE THREAD

**Issue by Palidino** [microsoft/vscode-java-debug#651]
Something with vscode or the plugin has changed in the last week, which causes the title'd error preventing java tasks from running.

##### Environment
- Operating System: MacOS Mojave 10.14.6
- JDK version: 1.8.0_191-b12
- Visual Studio Code version: 1.37.1
- Java extension version: Java Extension Pack v. 0.7.1
- Java Debugger extension version: Debugger for Java v. 0.21.0

##### Steps To Reproduce
Unknown, last worked on my project early in the week and was able to run a Java launch task with no issue. Only thing I can think of is either a vscode or plugin update broke something.

##### Current Result
Fails to launch debug task

##### Expected Result
Run the java code

##### Additional Informations
Another user confirmed he is unable to run it on both his Mac and Windows laptops as well. A closed issue (#164 - not sure how to link to issues instead of pulls) has multiple comments from the last few days saying they have the same issue all of a sudden.

**Comment by Palidino** [comment]
issue #637 of specifying internal console fixes the issue, but I don't feel like this should be the accepted solution

**Comment by testforstephen** [comment]
@Palidino In the new release, we changed the default debug console to integrated terminal. Could you share your integrated terminal snapshot?
![image](https://user-images.githubusercontent.com/14052197/64087389-602aea80-cd6f-11e9-84d0-2cf4f9338729.png)

**Comment by Eskibear** [comment]
Context:
`internalConsole` doesn't support stdin. In v0.21.0 we change the default console for debugging, from `internalConsole` to `integratedTerminal`, to enable the program to accept user input. 

We do find a similar issue for VSCode integrated terminal under MacOS, see #614 . The timeout might be caused by the incomplete command. So, when you would you check the terminal, see if the command is complete or not. 

For now, I suggest to switch to `internalConsole` as a workaround, or simply rollback to v0.20.0 (where internalConsole is the default value)

**Comment by metafaniel** [comment]
I still have this issue and the same workaround about `internalConsole` still works.
Will `integratedTerminal` will work someday as is or is there any other workaround to make it work?
Thanks in advance.

Visual Studio Code version: 1.64.2
Debugger for Java version: 0.38.0
