### ISSUE TITLE
conditional  breakpoint bug

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-java-debug#741]
https://github.com/microsoft/vscode/issues/87907#issue-544071046

**Comment by testforstephen** [comment]
![image](https://user-images.githubusercontent.com/14052197/71648615-97230400-2d41-11ea-8675-ee2387b6c240.png)

The error message `The literal ... is out of range` already told you the error reason. It's yourself using the wrong int constant.

**Comment by bonaluo** [comment]
The type of `Id` is `Long`, how can i use it to set conditional breakpoint.

**Comment by testforstephen** [comment]
The conditional breakpoint just accepts a valid boolean expression, run it and check it's return value. There is nothing special for the usage.

The problem is your expression is not a valid Java expression, it has compilation error. To verify it, you can paste your expression into the your Java file, it must not report compilation error.

**Comment by bonaluo** [comment]
The right way to debug long datatype is `jobEntity.getId().equals(new Long("-8316676600569574491"))`.Thank for your help.
