### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by tap90** [microsoft/vscode-java-debug#807]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version: 14
- Visual Studio Code version: 1.45
- Java extension version: 0.9.0
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
1. [step 1] 
I have OpenJDK 14 correctly configured. When I try to run my project I receive the follow error:

java.lang.UnsupportedClassVersionError: (class file version 56.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 58.65535

This class is a dependency and it is stored in a Nexus Repository, all this project have been compiled with JDK 12. So I try to uninstall OpenJDK 14 to install OpenJDK 12 but If I do this the project can't build because 'Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 14'.

But the same project is correctly build in Eclipse for example.
2. [step 2]

##### Current Result
java.lang.UnsupportedClassVersionError: (class file version 56.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 58.65535

If I switch JDK 14 -> JDK 12 - Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 14

##### Expected Result
Build And Run

**Comment by testforstephen** [comment]
The error explains itself. The error says the compiled class is 56.65535, but the runtime JDK only recognizes class file versoin 58.65535. That's because the preview feature is not backward compatible, i.e. JVM 14 doesn't support 12 preview feature. The [openjdk](https://openjdk.java.net/jeps/12) website has claimed the reason that it would be costly for JDK 14 to support preview features from JDK 12 which were changed or dropped in response to feedback.

**IMO**, you should not use a library that's compiled with preview flag, because preview feature is just a temporary feature and not backward compatible. If you don't use preview flag, actually JDK 14 can run normal  JDK 12 class.

> If I switch JDK 14 -> JDK 12 - Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 14

The build service is provided by vscode-java extension, in general only the latest JDK can enable preview.  If you still want to discuss enabling preview in JDK 12, please open an issue there. https://github.com/redhat-developer/vscode-java/issues

**Comment by testforstephen** [comment]
Please also try to add `"vmArgs": "--enable-preview"` to launch.json to see whether it works.

**Comment by tap90** [comment]
For everyone that has the same problem. 

I had to modify the .settings file which contained this line: 

org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled to org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=enabled 

Maybe visual studio code give some priority to eclipse settings that are in project. 

Than I add the vmArgs as suggested
