### ISSUE TITLE
The "Requirements" in the README.md might need a bit of an update.

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode-java-debug#896]
Per issue #852 , the requirements for the extension has been updated. However, the Readme.md file has not been updated to reflect upon the requirements that #852 laid out.

Currently, it says here:    (https://github.com/microsoft/vscode-java-debug#requirements)
 
>    JDK (version 1.8.0 or later)
>    VS Code (version 1.19.0 or later)
>    Language Support for Java by Red Hat (version 0.14.0 or later)

We should probably update the requirements, so that it includes additional information for specific VS Code for Java extension versions above a certain version.

**Comment by testforstephen** [comment]
If you are talking about Java debugger extension only, it still can run with the old VS Code Java extension such as 0.64.0 or before in JDK 1.8. That's why we don't update the requirement in the debugger side.

JDK 11 is only required when you are running Java Language Support for Java 0.65 or later.

**Comment by tommai78101** [comment]
I see. Looks like I got both the debugger and the Java Language Support for Java mixed up. Closing issue, since I am referring to the debugger itself.
