### ISSUE TITLE
--enable-preview is included when it shouldn't

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode-java-debug#933]
As the title says, see Steps to Reproduce below.

##### Environment
- Operating System: Windows 10
- JDK version: 16
- Visual Studio Code version: 1.53.0-insider
- Java extension version: 0.73.0
- Java Debugger extension version: 0.30.0

##### Steps To Reproduce
1. Java: Create Java Project... -> No build tools -> foo -> foo
2. click `Run` on the main method in the generated `App.java`

##### Current Result
The following command is launched:
```
& '...\VSCode-win32-x64-1.53.0-insider\data\extensions\vscjava.vscode-java-debug-0.30.0\scripts\launcher.bat' '...\jdk-16\bin\java.exe' '--enable-preview' '-XX:+ShowCodeDetailsInExceptionMessages' '-Dfile.encoding=UTF-8' '-cp' '...\VSCode-win32-x64-1.53.0-insider\data\user-data\User\workspaceStorage\ea3a630f16912c5698c408dd545ca16a\redhat.java\jdt_ws\foo_a53cc022\bin' 'App'
```
which fails with a LinkageError.

##### Expected Result
The same, but without `--enable-preview` in the command, so that the Java program would run.

**Comment by testforstephen** [comment]
![image](https://user-images.githubusercontent.com/14052197/104868243-d12b6c00-597d-11eb-9e76-67c99519ccf2.png)

This is what I get when I reproduce these steps. The debugger is just following your project's compliance level to determine whether to append "--enable-preview" flag. The root cause is that Java Language Support detects that your jdk is the latest version and then enables the preview flag when compiling your project, but Java Language Support currently only supports java 15, so the compiled class version is 59.65535 (jdk 15 preview).  Using jdk 16 can not run jdk 15 preview classes.



You have to open an issue at [vscode-java](https://github.com/redhat-developer/vscode-java/issues), tell it's compiler not to enable preview features when the user is using a not supported higher jdk.

**Comment by testforstephen** [comment]
here is the upstream issue https://github.com/eclipse/eclipse.jdt.ls/issues/1644
