### ISSUE TITLE
java.silentNotification should be renamed java.debug.silentNotification 

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-debug#967]
I was puzzled by "java.debug" not having that silentNotification setting, it took me a while to figure out it was directly under the "java" namespace.
https://github.com/microsoft/vscode-java-debug/blob/3987fe3f4859981978122e5d52c44a1eb6a17ada/package.json#L750

The "java" namespace is tacitly "owned" by vscode-java, so it would be much less confusing to rename the setting as java.debug.silentNotification.

**Comment by testforstephen** [comment]
i got your point. The background is the progress reporter interface could be extracted to a shared library once library extension is supported. It could be used by multiple Java extensions such as debugger, test runner, and even by other Java extensions as well. That's why we didn't put it in `java.debug` namespace.
